version: '3'
services:
  backend:
    image: guitvcer/djplay_backend_image:local
    container_name: djplay_backend_container
    build: backend/
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app/backend/
    command: bash -c "poetry run python3 manage.py makemigrations account gomoku chat &&
      poetry run python3 manage.py migrate &&
      poetry run python3 manage.py setup &&
      poetry run python3 manage.py runserver 0.0.0.0:8001"
    restart: always
  frontend:
    image: guitvcer/djplay_frontend_image:local
    build: frontend/
    container_name: djplay_frontend_container
    ports:
      - "8080:8080"
    command: npm run serve
    environment:
      - VUE_APP_BACKEND_HOST=localhost:8001
      - VUE_APP_RECAPTCHA_PUBLIC=6LdAUyUcAAAAANujUGnroaWZd6C5woLmMVpQdRtD
      - VUE_APP_GOOGLE_OAUTH2_PUBLIC=568731334008-liiq5eghbc2icnc51c4mrfcdcldsstvn.apps.googleusercontent.com
      - VUE_APP_VK_OAUTH2_PUBIC=7938245
    links:
      - backend
    restart: always